branches:
  only:
  - master
language: python

sudo: false

python:
    - '3.5'

before_install:
  - openssl aes-256-cbc -K $encrypted_26b4962af0e7_key -iv $encrypted_26b4962af0e7_iv
    -in ci.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp ssh_config ~/.ssh/config
  - git config --global push.default simple
  - git config --global user.name "xuanwo"
  - git config --global user.email xuanwo.cn@gmail.com
  - git clone -b gh-pages git@github.com:Xuanwo/CLIWiki.git output

install:
  - pip install simiki

script:
  - cp -r output/.git backup
  - rm -rf output
  - simiki generate
  - cp -r  backup output/.git
  - cp favicon.ico output
  - chmod ugo+x deploy.sh
  - ./deploy.sh
